name: Create config.js for Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create config.js from secret
        run: |
          echo "export const DESMOS_API_KEY = \"${{ secrets.DESMOS_API_KEY }}\";" >> config.js
          echo "export const API_ENDPOINT_URL = \"https://ko2hf5sz9g.execute-api.us-west-2.amazonaws.com/process\";" >> config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./